kitspace/kitspace-v2

frontend/.dockerignore, frontend/Dockerfile
- Initially, it was 1.16GB
- Now it is 334MB
- Further optimization should be done to the production version.
Even if it doesn't make a difference to the performance yet my hard drive is grateful.
=> Optimize Docker build

frontend/cypress/integration/updateProject.spec.js, frontend/src/hooks/Gitea.js, frontend/src/hooks/useForm.js, frontend/src/models/SearchFrom.js, frontend/src/pages/index.js, frontend/src/utils/giteaApi.js
=> Clean gitea hooks

.env.example, .github/workflows/docker.yml, docker-compose.yml, nginx/command, nginx/kitspace.template
To avoid getting our staging sites indexed by search engines. There are some better ways to avoid this (it's technically not correct to use robots.txt for this purpose I think) but this is the easiest for now.
=> Add robots txt defaulting to disallow

.github/workflows/docker.yml
Run integration tests on Chrome, Firefox, and Edge.
=> Browser matrix

frontend/src/components/Board/BuyParts/index.js, frontend/src/pages/[username]/[projectName]/index.js, frontend/src/utils/projectPage.js, processor/README.md, processor/src/tasks/processBOM/index.js, processor/src/tasks/processGerbers/gerber_files.js, processor/src/tasks/processGerbers/index.js, processor/test/integration/test_app.js
As discussed in https://github.com/kitspace/kitspace-v2/pull/74#issuecomment-850841145
=> Add input file info to processor json endpoints

frontend/src/hooks/useForm.js
=> Fix  checking "remember me"

frontend/cypress/integration/authRedirects.spec.js, frontend/cypress/integration/multiProject.spec.js, frontend/cypress/integration/navbar.spec.js, frontend/cypress/integration/signInForm.spec.js, frontend/cypress/integration/signUpForm.spec.js, frontend/cypress/integration/syncRepo.spec.js, frontend/cypress/integration/updateProject.spec.js
=> Use unique fake data (username/email)

frontend/src/utils/giteaApi.js, frontend/src/utils/giteaInternalApi.js, nginx/kitspace.template
=> Use `X-Csrf-Token` header instead of url param

frontend/cypress/integration/authRedirects.spec.js, frontend/cypress/integration/multiProject.spec.js, frontend/cypress/integration/syncRepo.spec.js, frontend/cypress/integration/updateProject.spec.js, frontend/cypress/integration/uploadProject.spec.js, frontend/cypress/support/commands.js, frontend/cypress/support/index.d.ts
=> Add `Cypress.forceVisit` command

frontend/cypress/integration/uploadProject.spec.js, frontend/src/components/DropZone.js, frontend/src/components/UploadModal.js, frontend/src/pages/_app.scss, frontend/src/pages/projects/new.js
=> Highlight drag and drop area when hovering

frontend/cypress/integration/signUpForm.spec.js, frontend/cypress/support/commands.js, frontend/src/pages/login.js
=> Remove success message on sign-up

frontend/cypress/integration/uploadProject.spec.js, frontend/cypress/support/index.js, frontend/package.json, frontend/yarn.lock
=> Upgrade Cypress@8.0

frontend/public/static/IBOM/index.js, processor/src/tasks/processIBOM/run_ibom, scripts/generate_ibom_index.sh
Fixes #144.
##
**Note**: prune the staging server before testing this, because the IBOM/index.js file is read from a volume.
=> Unify frontend and processor ibom

.github/workflows/docker.yml, README.md
- `ghcr` denied authentication.
- And as per [docs](https://github.com/docker/login-action#github-container-registry), we should use `GITHUB_TOKEN`.
=> Use `GITHUB_TOKEN` instead of `CR_PAT`

.github/workflows/docker.yml, frontend/cypress/integration/search.spec.js, frontend/src/contexts/SearchContext.js, frontend/src/hooks/Gitea.js, frontend/src/hooks/useForm.js, frontend/src/models/SearchFrom.js, frontend/src/pages/search.js, frontend/src/pages/search.module.scss
=> Fix redirecting to `/search` 

frontend/src/components/SharedProjectPage/elements.js, frontend/src/utils/giteaApi.js
closes #164, seems like csrf is needed
=> Fix checking collaborators causing 404

frontend/cypress/integration/multiProject.spec.js, frontend/cypress/integration/search.spec.js, frontend/cypress/integration/syncRepo.spec.js, frontend/src/components/NavBar/SearchBar.js, frontend/src/components/NavBar/index.js, frontend/src/components/NavBar/index.module.scss, frontend/src/components/Page.js, frontend/src/components/breakpoint.scss, frontend/src/contexts/SearchContext.js, frontend/src/pages/projects/new.js, frontend/src/pages/search.js
* Add loading status, closes #192.
* move the search input to the navbar, closes #196.
=> Improve search UX

frontend/cypress/integration/errorPage.spec.js, frontend/src/components/Error.js, frontend/src/pages/_error.js
=> Fix error messages

frontend/cypress/integration/signInForm.spec.js, frontend/cypress/integration/signUpForm.spec.js, frontend/src/hooks/useForm.js, frontend/src/models/SignInForm.js, frontend/src/pages/login.js
Instead of eagerly validating form fields, only validate fields on blur (moving focus to another element).
Fixes #94.
=> Fix form validation

frontend/.eslintrc.json, frontend/src/components/SharedProjectPage/elements.js, frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js, frontend/src/pages/[username]/[projectName]/index.js
=> Server vs client rendering

frontend/package.json, frontend/src/components/DropZone.js, frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js, frontend/src/pages/[username]/[projectName]/index.js, frontend/yarn.lock
Reject all the files under the `.git` folder when uploading.
##
Fixes #238
=> Prevent uploading `.git` folder

.github/workflows/lint-processor.yml, processor/.eslintrc.json, processor/.prettierignore, processor/package.json, processor/src/checkIsRepoReady.js, processor/src/env.js, processor/src/projectAPI.js, processor/src/remoteAPI.js, processor/src/tasks/processBOM/get_partinfo.js, processor/src/tasks/processBOM/index.js, processor/src/tasks/processGerbers/board_builder.js, processor/src/tasks/processGerbers/findGerberFiles.js, processor/src/tasks/processGerbers/index.js, processor/src/tasks/processIBOM/index.js, processor/src/tasks/processKicadPCB/index.js, processor/src/tasks/processReadme.js, processor/src/utils.js, processor/src/watcher.js, processor/src/workers.js, processor/tsconfig.json, processor/yarn.lock
Runs `tsc` and `eslint` on the processor. Fixes #117
=> Typecheck and lint the processor

.github/workflows/auto-merge.yml, .github/workflows/docker.yml, scripts/get_open_pull_requests.py, scripts/merge_open_pull_requests.py
This action auto-merges all open pull-requests, that are ready for review, into a "review" branch and leaves comment on those PRs as to wether it succeeded. The review branch is auto-deployed to https://review.staging.kitspace.dev. It does this from scratch every time something is pushed to a PR or it's opened, re-opened, marked for review etc. or if the master branch changes.
=> Add an auto-merge action

processor/src/projectAPI.js, processor/src/remoteAPI.js, processor/src/watcher.js, processor/src/workers.js
Addresses comment on https://github.com/kitspace/kitspace-v2/pull/243#discussion_r793895487
=> Refactor processor events

frontend/cypress/integration/authRedirects.spec.js, frontend/cypress/integration/signInForm.spec.js, frontend/cypress/integration/signUpForm.spec.js, frontend/src/pages/login/index.js
=> Simplify switching tabs in /login

frontend/src/components/Board/BuyParts/MpnPopup.js, frontend/src/components/Board/BuyParts/TsvTable.js, frontend/src/components/SharedProjectPage/elements.js, frontend/src/pages/[username]/index.js, frontend/src/pages/login/index.js, frontend/src/pages/projects/new.js, frontend/src/pages/search/index.js, frontend/src/utils/projectPage.js, frontend/yarn.lock
Note this is against the `frontend-upgrade-deps-2` not `master`.
=> Remove `babel-plugin-lodash`

frontend/cypress/integration/IBOM.visual.spec.js, frontend/src/components/NavBar/index.js, frontend/src/components/NavBar/index.module.scss
I think this fixes #266. I'm still confused about this one though, about the ref passing etc. not sure what it was for at all. I never saw any warnings about it. Maybe it was fixed?
=> Fix blinking of logo component on Firefox

frontend/package.json, frontend/src/components/LiteYouTube/index.js, frontend/src/components/LiteYouTube/index.module.scss, frontend/src/pages/bom-builder.js, frontend/yarn.lock
=> Switch to ` @justinribeiro/lite-youtube` for videos

processor/src/remoteAPI.js, processor/src/tasks/processBOM/index.js, processor/src/tasks/processGerbers/index.js, processor/src/tasks/processIBOM/index.js, processor/src/tasks/processKicadPCB/index.js, processor/src/tasks/processPCB.js, processor/src/tasks/processReadme.js, processor/src/tasks/processSchematics/index.js, processor/src/tasks/writeKitspaceYaml.js, processor/src/watcher.js, processor/src/workers.js
Just the refactoring from #298 without enabling schematic processing for repos.
=> Refactor processor

frontend/.eslintrc.json, frontend/src/components/LiteYouTube/index.js, frontend/src/components/SharedProjectPage/elements.js, frontend/src/components/SharedProjectPage/index.js, frontend/src/contexts/SearchContext.js, frontend/src/pages/[username]/[projectName]/index.js, frontend/src/utils/giteaApi.js, frontend/src/utils/projectPage.js
=> Fix re-importing `lite-youtube` on re-rendering

frontend/cypress/integration/Readme.spec.js, processor/src/tasks/processReadme.ts
Add the check mentioned in #310.
=> e2e: check README images URLs are working

frontend/cypress/integration/search.spec.js, frontend/src/components/NavBar/SearchBar.js
=> Fix search submission in Firefox

.github/workflows/docker.yml, README.md, docker-compose.e2e.yml, e2e/Dockerfile, e2e/entrypoint.sh, e2e/package.json
Fixes #341
##
@kasbah, could you try all three options in the readme to make sure everything is OK?
=> Run e2e in docker locally

frontend/src/pages/projects/new/index.js
=> Fix setUserOp can be undefined

.github/workflows/docker.yml, docker-compose.e2e.yml, e2e/entrypoint.sh
Fixes ##355
##
I believe this will fix the badge too!
=> e2e: add version control info when running inside docker

.github/workflows/docker.yml
=> CI: wrap environment variables in quotes

frontend/src/components/Board/BuyParts/index.js, frontend/src/components/Board/BuyParts/index.module.scss
Fixes #346
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/170845997-f5cf7c22-2ff6-49f2-92b8-17213b0fb858.png)|![image](https://user-images.githubusercontent.com/37152329/170846148-cff87c83-c635-4fc1-8b7e-ce69ce25e6f6.png)|
=> Disable `Buy Parts` section when there is no purchasable parts

e2e/cypress/integration/syncRepo.spec.js, frontend/src/components/SharedProjectPage/index.js, frontend/src/utils/giteaApi.js
=> Add service information when syncing repos

README.md, e2e/cypress/integration/IBOM.spec.js, frontend/src/components/Board/BoardExtrasMenu.js, frontend/src/utils/projectPage.js, processor/src/tasks/processIBOM/index.ts
As mentioned in https://github.com/kitspace/kitspace-v2/issues/347
##
Fixes #347
=> Support `omit-ibom` option in `kitspace.yaml`

frontend/src/components/Error/index.js, frontend/src/pages/_error.js
=> Fix: use `@components/Head` in `_eror.js`

e2e/cypress/integration/multiProject.spec.js, processor/package.json, processor/src/queues.ts, processor/yarn.lock
=> Handle sub project names with special characters

e2e/Dockerfile, e2e/entrypoint.sh
Fixes #413
##
Tested it in cfd68d45ee7775588800657b31301afafe9af09e and cbd7a6a9ee74ee1edfe0a3b89eb4cbc3585a9865.
=> Escape commit message when passing it to cypress

e2e/cypress/integration/IBOM.spec.js, e2e/cypress/integration/IBOM.visual.spec.js, e2e/cypress/integration/Readme.spec.js, e2e/cypress/integration/multiProject.spec.js, e2e/cypress/integration/search.spec.js, e2e/cypress/integration/syncRepo.spec.js
=> Move all test repos to the `kitspace-test-repos` org

processor/package.json, processor/src/queues.ts, processor/yarn.lock
- Debug: I think the flakiness is caused by a race condition in the `sync` fuction
- Deps: add `async-lock`
- Fix: prevent race condition in `sync(gitDir, checkoutDir)`
=> Fix race condition in the `sync` function

processor/package.json, processor/src/tasks/processBOM/index.ts, processor/src/tasks/processGerbers/index.ts, processor/src/tasks/processKicadPCB/index.ts, processor/src/tasks/processReadme.ts, processor/src/tasks/processSchematics/index.ts, processor/test/integration/test_projects.ts, processor/yarn.lock
- Fixes #381: https://abdo-dev.staging.kitspace.dev/tester2/tinyogx360
- Fixes #379: https://abdo-dev.staging.kitspace.dev/tester2/OpenXenium
- Fixes #377: https://abdo-dev.staging.kitspace.dev/tester2/XboxHDMI-Ryzee119
=> Fix ignoring hidden directories when searching for PCB files

frontend/src/components/Board/BuyParts/index.js
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/192796878-e381b7d6-c7f4-41f9-b82e-d6db89f41d26.png)|![image](https://user-images.githubusercontent.com/37152329/192797014-59b7381a-953d-4ecf-845d-ea9aef3bc213.png)|
Fixes #423
=> Show BOM even if there's no purchasable parts

processor/src/queues.ts, processor/src/remoteAPI.ts, processor/src/tasks/processGerbers/index.ts, processor/src/tasks/processIBOM/index.ts, processor/src/tasks/processKicadPCB/index.ts, processor/src/tasks/processSchematics/index.ts, processor/src/utils.ts, processor/test/integration/test_projects.ts
=> Escape the plot commands for `plotKicadGerbers` & `plotKicadLayoutSvg`

e2e/cypress/integration/readme.spec.js, processor/package.json, processor/src/queues.ts, processor/yarn.lock
=> Replace slugify sub project names with `formatAsGiteaRepoName`

e2e/cypress/integration/syncRepo.spec.js
#468 is affecting other PRs so skipping these tests for now.
=> e2e: skip description fallback tests

frontend/public/static/IBOM/index.css
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/201866804-c91eaa92-eabb-45e4-9ce7-bbb87c76859b.png)|![image](https://user-images.githubusercontent.com/37152329/201867072-d7bf9639-2b51-426c-bd9c-cbaf76011f33.png)|
=> Fix IBOM dark mode

frontend/src/components/Board/IBOM.jsx
=> Fix IBOM script loading and execution

frontend/src/components/NavBar/index.jsx, frontend/src/components/NavBar/index.module.scss
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/203772170-02d8afe0-7f11-4b1a-b852-2303f585a1cb.png)|![image](https://user-images.githubusercontent.com/37152329/203771999-9372ec76-892c-44a6-8c9c-9570b20ed6eb.png)|
##
Fixes #505
=> Fix `Add a project` button style

frontend/src/components/Board/IBOM.jsx
|before|v2|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/201898071-31d57917-0fc1-47d8-a550-aeba01b7d5b0.png)|![image](https://user-images.githubusercontent.com/37152329/201897742-0b2e94a2-6dce-402c-ac36-19bd5fda0b1c.png)|
##
Based on #497
=> Include sub project name in IBOM title

.github/workflows/docker.yml
We will re-enable it after fixing #508.
=> Disable firefox e2e for now

frontend/src/components/ProjectCard/index.module.scss, frontend/src/components/ProjectCard/index.tsx
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/207318309-95d9e3f8-3439-4723-988f-0a0baee44aa9.png)|![image](https://user-images.githubusercontent.com/37152329/207318137-28ec13af-fecd-4b2e-a464-516ef5557926.png)|
##
Fixes #522
=> Fix card font weight and color

frontend/src/components/ProjectCard/index.tsx, frontend/src/components/ProjectCardGrid/index.tsx, frontend/src/hooks/useThumbnail.js
Fixes #510 
> Maybe we should use imageset or let next/image do its magic here?
`next/image` uses `srcset` so I used `top-large.png` and delegated optimization to next.
=> Improve card thumbnail

e2e/cypress/integration/IBOM.spec.js, frontend/next.config.js, frontend/src/components/Board/BoardExtrasMenu.jsx, frontend/src/components/SharedProjectPage/elements.jsx
=> Stop serving IBOM at `[user]/[repo]/IBOM`

processor/README.md
Add `--recursive` flag to make sure that all files are actually cleared.
=> Update docs for clearing s3 buckets

processor/src/tasks/processKicadPCB/index.ts, processor/test/integration/projects.test.ts
=> Plot gerbers if `gerbers` is an archive

frontend/src/hooks/s3HeadFetcher.ts, frontend/src/hooks/useKitspaceYAML.js, frontend/src/hooks/useProjectAssets.js, frontend/src/hooks/useThumbnail.js
Fixes #507.
It won't cause any performance issues; the body size is zero.
=> Don't cache `useProjectAsset` head request

processor/src/tasks/processReadme/renderMarkdown.ts, processor/src/utils.ts, processor/test/unit/readme_processing.test.ts
=> Don't treat emails as relative URLs in the README

ansible/requirements.txt
`ansible-core` needed a bump too. I ran the `check` script and everything is OK.
=> Bump ansible-core from 12.13.5 to 12.14.0 in /ansible

processor/src/job.d.ts, processor/src/queues.ts, processor/src/tasks/addToSearch.ts, processor/src/tasks/cleanUp.ts, processor/src/tasks/processBOM/index.ts, processor/src/tasks/processGerbers/index.ts, processor/src/tasks/processIBOM/index.ts, processor/src/tasks/processInfo.ts, processor/src/tasks/processKicadPCB/index.ts, processor/src/tasks/processPCB.ts, processor/src/tasks/processReadme/index.ts, processor/src/tasks/writeKitspaceYaml.ts, processor/src/workers.ts
Use bullmq flows to clean up the dir after finishing all jobs for the repo.
##
Fixes #537
=> Clean up input dir after finishing all jobs in a repo

scripts/README.md, scripts/importBoardsTxt.ts
=> Shuffle boards in `importBoardsTxt.ts` script

processor/Dockerfile, processor/src/tasks/processIBOM/run_ibom, processor/src/tasks/processKicadPCB/plot_kicad_pcb, processor/src/tasks/processKicadPCB/shrink_svg.py, processor/src/tasks/processKicadPCB/util.py, processor/test/integration/projects.test.ts
- Upgrade our scripts to KiCad 7
- Upgrade IBOM for compatibility, IBOM has native Eagle support now so we no longer need to convert those to KiCad
=> Upgrade to KiCad 7

.github/workflows/auto-merge.yml, .github/workflows/copy-import-script.yml, .github/workflows/docker.yml, .github/workflows/lint-frontend.yml, .github/workflows/lint-processor.yml, .github/workflows/test-frontend.yml, .github/workflows/test-processor.yml
Support for the old way is going to be removed at the end of the month.
=> Update use of `set-output` to `>> $GITHUB_OUTPUT`

.github/workflows/docker.yml
Getting errors with getting the images because the format was updated (to support multi-arch I think?)
=> Update ghcr manifest content type

frontend/next.config.js, frontend/src/components/Board/BuyParts/index.jsx, frontend/src/server.js
=> Connect up 1-click-BOM extension

frontend/next.config.js, frontend/src/components/Head.jsx, frontend/src/components/Page/index.jsx, frontend/src/components/SharedProjectPage/index.jsx, frontend/src/pages/[user]/[repo]/[project]/index.jsx, processor/src/tasks/writeKitspaceYaml.ts
=> Add project page meta tags

processor/src/app.ts, processor/src/healthChecks.ts
=> Add healthchek for `partinfo.kitspace.org`

processor/src/queues.ts
=> Return after lock release when syncing repos

docker-compose.deploy.yml, docker-compose.override.yml, docker-compose.yml, e2e/cypress/support/commands.js, processor/src/giteaDB.ts, processor/src/healthChecks.ts, scripts/importBoardsTxt.ts
Drop d1add0a, when `partinfo` is back
=> Switch to go-gitea docker image

frontend/src/pages/newsletter/index.module.scss, frontend/src/pages/newsletter/index.tsx
The subscription submission hasn't been handled yet.
=> Port `/newsletter` from v1

frontend/src/pages/_document.tsx
=> Add Google fonts

frontend/next.config.js
=> legacy custom redirects

.github/workflows/copy-import-script.yml, scripts/importBoardsTxt.ts
This is actually mainly to get it to copy it over again as I deleted it.
=> Slightly simplify copy-import-script workflow

frontend/src/components/Board/BuyParts/index.module.scss, frontend/src/components/Board/BuyParts/index.tsx
PR for your branch @AbdulrhmnGhanem. Changing the button icons to:
=> Change buy parts label icons to "link" or "download"

processor/src/tasks/processBOM/index.ts
=> Fix BoM encoding

frontend/src/pages/_app.jsx
=> Include plausible script on kitspace.org

frontend/src/components/Board/OrderPCBs.jsx
=> Remove JLC PCB

processor/src/tasks/processReadme/index.ts, processor/src/tasks/processReadme/renderMarkdown.ts, processor/src/tasks/processReadme/urlTransformer.ts, processor/src/utils.ts
For readme of https://github.com/OpenDosimeter/OpenDosimeter
=> Fixup readme processing for Bibtex and GitHub /user-attachments

processor/package.json
For https://github.com/OpenDosimeter/OpenDosimeter BOM
=> Update npm-1-click-bom for better "count" matching

frontend/package.json, frontend/src/components/Board/BuyParts/Bom.tsx, frontend/yarn.lock
It's not being updated for latest react
=> Remove react-double-scrollbar

boards.txt
Adds 3 new boards that were missing from kitspace v1. Glad to see kitspace v2 around! ❤️
=> Add new OpenGammaProject boards
