kitspace/kitspace-v2

Dockerfile.gitea.dev
docker-compose.production.yml
docker-compose.yml

closes #23 
With this, `docker-compose up gitea` will run `make backend` before starting gitea, so our changes to gitea will be compiled in an effecient way.

Add a gitea dev docker container config

---

docker-compose.yml
frontend/package.json
frontend/server.js
frontend/src/hooks/Gitea.js
frontend/src/pages/1-click-bom.js
frontend/src/pages/bom-builder.js
frontend/src/pages/index.js
frontend/src/pages/projects/[user].js
frontend/src/pages/projects/mine.js
frontend/src/pages/projects/new.js
frontend/src/pages/projects/update/[user]/[projectName].js
frontend/src/utils/giteaApi.js
frontend/yarn.lock

SSG causes some problems because of the way `_app.js` set up.
* Add `UserExists` util function.
* SSR `mine` page.
* Migrate all pages: SSG -> SSR.
- The way authentication works breaks SSG in production. SSR is the next best thing!
- It worked before because Next re-run the build on each request in development, see [docs](https://nextjs.org/docs/basic-features/data-fetching#runs-on-every-request-in-development)
* Configure frontend logger for production.
- Previously there was no output from when running in production.
* Remove `ref` from the `useDefaultBranchFiles`.
- Gitea returns the files in the default branch if there's no ref provided.

Migrate from SSG to SSR

---

.github/workflows/docker.yml
README.md

I'm switching the auto-deploys domain to .dev because we could run into cookie issues when we finally deploy to the apex domain on .org. Additionally I've created two separate auto-deploys for our own branches. So the master branch deploy is now:
https://master.staging.kitspace.dev (hopefully we will see something here when this is merged) 
@AbdulrhmnGhanem you can push whatever you want to the `abdo-dev` branch and this should be deployed to:
https://abdo-dev.staging.kitspace.dev
I've added your public ssh key to authorized_keys so you should be able to login with `ubuntu@abdo-dev.staging.kitspace.dev`  when there are any issues (which there probably will be occasionally). 
My own branch is `kaspar-dev` which is deployed to: https://kaspar-dev.staging.kitspace.dev. We should make the e2e …

.dev auto-deploys

---

.github/workflows/docker.yml

https://docs.cypress.io/guides/guides/parallelization#Grouping-test-runs
- Previously, all tests used the default group which made the results of each browser overwrites other browsers.
- Groups are needed for parallelization if a testing matrix (in our case multiple browsers) is used.

Add Cypress test runs groups

---

frontend/cypress/integration/uploadProject.spec.js
frontend/src/pages/projects/new.js

Fixes #90.
##
- The rename button is "OK" after changing the name.
- The upload to the same project is `Add file to ${projectName}`.
##
##
##

Fix conflicting project names modal

---

frontend/src/components/Page.js

Fixes #152.
- The problem isn't with data fetching because Next only redirects when the data is ready when using `getServerSideProps`. Actually, this loader has no idea about the loading status of the content.
- The authentication status is read from `window.session` not a remote source, suspense won't make a difference here.
- Loaders were displayed to prevent flashing content for protected paths.
- Paths neither marked as `requireSignIn` nor `requireSingOut` are considered public paths; users can see its content whether they are logged in or not.
-Throttle loaders for authenticated routes. Leave a period in which the loader doesn't show up, during this period the `loading` state changes which results in flashing the loader.

Avoid flashing loaders for public paths

---

processor/README.md
processor/src/watcher.js
processor/test/integration/test_projects.js
processor/test/integration/test_remote.js

It's taking up too much processor time, pegging 2-cores at 100% on our staging server.

Disable schematic processing

---

frontend/cypress/integration/search.spec.js
frontend/cypress/integration/syncRepo.spec.js
frontend/cypress/integration/uploadProject.spec.js
frontend/cypress/support/getFakeUsername.js
frontend/src/components/Board/InfoBar.js
frontend/src/components/SharedProjectPage/elements.js
frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js
frontend/src/pages/[username]/[projectName]/index.js
frontend/src/pages/search.js

Based on #179.
- 46feeff: Update gitea submodule @730051a63, see https://github.com/kitspace/gitea/pull/18.
- https://github.com/kitspace/kitspace-v2/commit/0af83ab92cce97274155f207e687317fa8c8d1d8: Add e2e test `should display original url for synced repos`.
##
The problem was in the migration logic, not the presentation layer. To see the result, sync a new repo.

Fix missing `original_url` for synced repos

---

.vscode/launch.json
docker-compose.override.yml
frontend/package.json
frontend/yarn.lock

- Run the node process for the frontend with the `inspect` option,
- This required dropping `nodemon`;
- running the server with `nodemon` will spawn two different processes which will make the `nodemon` process (the first one to get initialized) acquire the exposed port (9229) and server.js (the actual target we are trying to debug) fails.
- Though the tradeoff is acceptable because `server.js` rarely change.
- This will enable debugging within VSCode, which includes **CPU and memory profiling, and setting breakpoints** or using the Chrome dedicated node
debugger.
- This won't affect the normal workflow, the debugger gets attached if you run the debugger from VSCode! :sweat_smile: 
- A similar approach can be used with the processor to add support for the debugger if needed.

Support debugging frontend from VSCode

---

frontend/src/components/Board/BoardShowcase.js

Fix board showcase layout-shift after loading images

---

.github/workflows/docker.yml

When trying a branch (deploying it to staging), the docker images get unnecessarily rebuilt.
This reduced the [first time build](https://github.com/kitspace/kitspace-v2/runs/3603738809) from `5m 4s` to `1m 39s` for [redeployment build](https://github.com/kitspace/kitspace-v2/runs/3603794357?check_suite_focus=true).

Avoid rebuilding images when deploying already built images

---

frontend/src/components/Board/BuyParts/InstallPrompt.js
frontend/src/components/ProjectCard.js
frontend/src/pages/1-click-bom.js
frontend/src/pages/bom-builder.js
frontend/src/pages/search.js

- Render `ProjectCard` as an `a` tag.
- Wrap plain text links in the `<a>` tag.
- Fixes #209 
- See https://github.com/vercel/next.js/discussions/29496

Fix not prefetching `Link`s

---

frontend/cypress/integration/errorPage.spec.js
frontend/src/pages/404.js
frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js
frontend/src/pages/[username]/[projectName]/index.js
frontend/src/pages/_error.js
nginx/kitspace.template

Fixes #211 
##
- See https://github.com/kitspace/gitea/pull/19/commits/eca2dd04feeff97c69a810c67c58793b45499abf
- For `getServerSideProps` returning `{ notFound: true}` is sufficient to return `404` as status code for the document.
- For `getInitialProps` had to set the status code manually on the `res` object. (Setting the status code in `ErrorPage.getIntialProps` doesn't work).

Fix mismatch between error pages and its status response

---

frontend/package.json
frontend/src/pages/search/index.js
frontend/yarn.lock

Sometimes the homepage returns 500 because one of the requests in the`getServerSideProps` failed. It uses exponential backoff to prevent it from flooding the server with requests if the failure is due to high traffic.

Make homepage fault-tolerant when requesting its data

---

frontend/cypress/integration/IBOM.spec.js
frontend/cypress/integration/multiProject.spec.js
frontend/src/components/Board/IBOM.js
frontend/src/pages/[username]/[projectName]/IBOM.js
frontend/src/pages/[username]/[projectName]/[multiProjectName]/IBOM.js

- redirect to subproject on clicking the card on multi-project page
- For multi-project, visiting `/[username]/[projectName]` displays a
grid of subprojects. Clicking on any of the cards didn't redirect to
the correct subproject page.
- Update `multi-project.spec` to catch this bug.
- clicking on the IBOM title for multi-project doesn't redirect to the project page.
- Added tests for this case for normal and multi-projects

Fix multi projects redirect

---

processor/src/tasks/processReadme.js

- Destructure the right name for the project: `name` not `projectFullname`.

Fix `processReadme`

---

frontend/src/components/NavBar/index.js

This actually solves most of what I was complaining about with https://github.com/kitspace/kitspace-v2/issues/272 (I was mostly clicking on these menu items). There seems to be a bit of "blinking" still. I think that's down to the way stuff is painted before auth is checked. The brief flash of the spinner on the project pages is another matter.

Fix menu items not using next/link

---

frontend/cypress.json
frontend/cypress/integration/authRedirects.spec.js
frontend/src/components/Page.js
frontend/src/pages/index.js
frontend/src/utils/authHandlers.js

The [main change is in gitea](https://github.com/kitspace/gitea/compare/d1342b36f1b5e4ac0271d0f01c5270cd087f3575...351aea301fad4e9084962870764d5a407e008a8c#diff-e5ab7b7f38f5bdc95204c297cb135ee314e614b2cc24e577aa20a27afcf4d604). Sorry about this one @AbdulrhmnGhanem. I realise the way this was behaving was really confusing.  It must have warped you understanding of http re-directs :D 
In the long run I will try and get rid of the `/__kitspace` hack. I think my own understanding of http and csrf prevention was lacking when I came up with it and we should be able to come up with something more sensible.

Fix redirects not being passed to browser

---

.github/workflows/docker.yml

Cut the runtime for e2e by a factor of 4. The serial version runs in ~14.5 mins, the parallel version runs in ~5 mins.

Re-enable running e2e in parallel

---

frontend/cypress/integration/IBOM.spec.js
frontend/src/pages/[username]/[projectName]/IBOM.js
frontend/src/pages/[username]/[projectName]/[multiProjectName]/IBOM.js
frontend/src/pages/[username]/[projectName]/[multiProjectName]/index.js
frontend/src/pages/[username]/[projectName]/index.js
frontend/src/pages/_error.js

Visiting the Ibom page for nonexistent project returns `500`.

404 instead of 500 for `ibom` page if the project doesn't exist

---

.env.example

I think something about how docker-compose escapes the envs changed. I recently updated to `Docker Compose version 2.3.3` and was getting `sed` errors. Can you check if changing this in your .env breaks your nginx @AbdulrhmnGhanem.

Fix bad substitution error for nginx

---

.github/workflows/docker.yml

Limit e2e matrix across all browsers to `push` events on `master`

---

processor/src/app.ts
processor/src/projectAPI.ts
processor/src/remoteAPI.ts
processor/src/tasks/processGerbers/index.ts
processor/src/watcher.ts
processor/src/workers.ts

Fixes the memory issue of the processor we encountered testing out the d20 project. 
- Uses `jobId` to not start jobs that are already in progress
- Limits worker concurrency to 1 (i.e. no concurrency of an individual worker type)
- Removes concurrency of `inkscape` executions which take up a lot of memory
d20 was now imported without issue on https://review.staging.kitspace.dev/ 
Additionally it now removes/`obliterates` all queues when stopped (which clears out the redis data). This was needed for the integration tests, probably should make use of this when exiting during normal operation as well.

Fix processor running out of memory

---

frontend/tsconfig.json

Without it, the editor can't resolve the `@` paths correctly. This broke refactoring and view source functionalities in VSCode.

Include `.js` files in `tsconfig`

---

processor/src/tasks/processReadme/urlTransformer.ts
processor/test/integration/test_readme_processing.ts

If an `a` element doesn't have a `href` attribute or an `img` element doesn't have a `src` attribute it would break our readme URL transformer. 
For example https://github.com/8BitMixtape/8BitmixtapeNEO_ShenzhenReady readme is
```
summary: <a summary for your project> <- This invalid <a>  tag, probably it's meant as a placeholder
site:https://8bitmixtape.github.io/NeoWiki
```
##
Fixes #437

Handle readme `a` and `img` elements with no URLs

---

docker-compose.override.yml
docker-compose.yml
frontend/Dockerfile
processor/.dockerignore
processor/Dockerfile
scripts/clear_volumes_and_test_processor.sh

While investigating #450 I noticed the server runs as `root` which can lead to [some issues](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/non-root-user.md).

Stop running `frontend` and `processor` with root user

---

processor/package.json
processor/src/tasks/processGerbers/index.ts
processor/src/tasks/processKicadPCB/index.ts
processor/test/integration/generateImageHash.ts
processor/test/integration/test_projects.ts
processor/tsconfig.json
processor/yarn.lock

 Use plotted gerbers when `eda` is available

---

frontend/package.json
frontend/src/pages/login/index.jsx
frontend/src/pages/projects/new/index.jsx
frontend/src/pages/settings.jsx
frontend/src/utils/authHandlers.js
frontend/yarn.lock

I blew away the lockfile for some experiments with using pnpm and noticed `next-composition` has a breaking change 1.0 -> 1.1 (it stops returning  empty`{props: {}}` by default). I also noticed that we aren't really using it for anything useful and it's making the code less clear. Hence I am removing it.

Remove next-composition

---

processor/src/tasks/addToSearch.ts

Projects with a `.` in the name  (e.g., `sangaboard_v0.3`) weren't getting added to meilisearch.

meilisearch: make document id compliant with the spec

---

e2e/cypress/integration/IBOM.spec.js
e2e/cypress/integration/IBOM.visual.spec.js
e2e/cypress/integration/authRedirects.spec.js
e2e/cypress/integration/multiProject.spec.js
e2e/cypress/integration/readme.spec.js
e2e/cypress/integration/search.spec.js
e2e/cypress/integration/signInForm.spec.js
e2e/cypress/integration/signUpForm.spec.js
e2e/cypress/integration/syncRepo.spec.js
e2e/cypress/integration/uploadProject.spec.js
e2e/cypress/support/getFakeUser.js
frontend/src/hooks/useForm.ts
frontend/src/models/SignInForm.js
frontend/src/models/SignUpForm.js

- e2e: use faker `userName` instead of `firstName` and @example emails.
- Make validation rules for `Sign{Up,In}Form` match gitea.
##
Fixes #482 and closes #481

Fix e2e names and emails and make validation rules for `Sign{Up,In}Form` match gitea

---

e2e/cypress/integration/authRedirects.spec.js
frontend/package.json
frontend/src/components/Board/Readme.jsx
frontend/src/components/Board/readme.module.scss
frontend/src/components/NavBar/fixNavBarAlignment.module.scss
frontend/src/components/NavBar/index.jsx
frontend/src/components/NavBar/index.module.scss
frontend/src/pages/_app.scss
frontend/yarn.lock

- Refactor: move SmallMenu style into its SCSS module
- Refactor: replace styled-jsx with scss file for items alignment
- Refactor: replace styled-jsx with scss file for readme
- Deps: remove styled-jsx
##
|before (menu)|after (menu)|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/201411367-146118a8-f76e-46b4-a2d5-d75dd95413da.png)|![image](https://user-images.githubusercontent.com/37152329/201411506-227d3d30-91cd-48e4-a6b0-ff0bae962073.png)|
|before (readme)|after (readme)|
|---|---|
|![image](https://user-images.githubusercontent.com/37152329/201412150-e095f5dd-d800-4000-b999-e514e76371cc.png)|![image](https://user-images.githubusercontent.com/37152329/201412431-04d31af2-a8d0-475a-a0a1-590c95d1d0b5.png)|
##
Closes #269.

Remove styled-jsx

---

.github/workflows/docker.yml
README.md

I think this is clearer and more useful than having a `latest` tag. When you notice issues in CI e2e or staging which you can't reproduce with the dev version then you can do something like this in .env:
```
FRONTEND_DEPLOY_IMAGE_TAG=:kaspar-dev
PROCESSOR_DEPLOY_IMAGE_TAG=:kaspar-dev
NGINX_DEPLOY_IMAGE_TAG=:kaspar-dev
GITEA_DEPLOY_IMAGE_TAG=:kaspar-dev
```
and 
```
docker-compose -f docker-compose.yml -f docker-compose.deploy.yml -f docker-compose.e2e.yml
```
To reproduce locally.

Tag docker images with branch name instead of "latest"

---

e2e/cypress/integration/IBOM.spec.js
e2e/cypress/integration/readme.spec.js
processor/src/tasks/processReadme/urlTransformer.ts

I'm not totally sure what this test was supposed to be testing for since the test and `data-cy` talked about "relative" images but two of them were remote images and the other two were in the repo, so I dunno, "relative" to what? The main problem though is the remote images are private now so I've updated the test repo. 
Also, I should probably add floating promise eslint to e2e and frontend (the promise was floating and hence the assert wasn't in the test from cypress perspective, it still failed the test when it should but the error message was a bit more confusing than it needed to be). 
Fixes https://github.com/kitspace/kitspace-v2/issues/479

Fix e2e test for readme images

---

processor/src/tasks/processGerbers/index.ts
processor/src/tasks/processIBOM/index.ts
processor/src/tasks/processKicadPCB/index.ts
processor/src/tasks/processPCB.ts

Removes all the temp files and those that get uploaded to s3. Just deleting everything at the end of the processing would have been easier but I decided to keep the removal of files as close as possible to the creation of the files. I think it makes more sense this way because it decouples the tasks from the rest of the app.

Delete processor intermediate files

---

processor/.eslintrc.json
processor/src/giteaDB.ts
processor/src/meili.ts
processor/src/queues.ts
processor/src/tasks/addToSearch.ts
processor/src/tasks/processBOM/index.ts
processor/src/tasks/processGerbers/index.ts
processor/src/tasks/processIBOM/index.ts
processor/src/tasks/processKicadPCB/index.ts
processor/src/tasks/processReadme/index.ts
processor/src/tasks/writeKitspaceYaml.ts
processor/src/watcher.ts
processor/test/integration/projects.test.ts

Seems like the style I adopted of just "floating" all the `job.updateProgress` makes things less predictable without much gain.

Remove all instances of floating promises in processor

---

processor/package.json
processor/src/queues.ts
processor/src/shell.ts
processor/src/tasks/processGerbers/index.ts
processor/src/tasks/processIBOM/index.ts
processor/src/tasks/processKicadPCB/index.ts
processor/src/utils.ts
processor/test/integration/projects.test.ts
processor/yarn.lock

I just realized template tags are made for this kind of thing. It escapes anything that comes in via a variable. I vendored and modified shell-escape since it's quite a simple function actually. 
closes #465

Replace `execEscaped` with a template tag

---

e2e/cypress/integration/multiProject.spec.js
e2e/cypress/integration/search.spec.js
frontend/src/components/NavBar/SearchBar.module.scss
frontend/src/components/NavBar/SearchBar.tsx
frontend/src/components/NavBar/index.jsx
frontend/src/components/ProjectCardGrid/index.tsx
frontend/src/components/breakpoint.scss
frontend/src/contexts/SearchContext.tsx
frontend/src/hooks/useLazySearch.ts
frontend/src/pages/[user]/[repo]/index.tsx
frontend/src/pages/_app.scss
frontend/src/pages/search/index.module.scss
frontend/src/pages/search/index.tsx
frontend/test/Copy.test.tsx
frontend/test/IntroText.test.tsx
frontend/test/fixtures/Copy.json

- Refactor: `SearchContext.jsx` -> `SearchContext.tsx`
- UI: improve `mobile_menu` breakpoint
- UI: make the search bar usable in homepage too
- UI: add search bar in home page for small devices
- e2e: `Homepage search on mobile`
##
Fixes #511.

Add the IntroText and mobile homepage search bar

---

e2e/entrypoint.sh

I found escaping the commit body may be unnecessarily complicated and we don't need it in the cypress dashboard. So I removed it.
I rebased the depedabot commit on top of this commit to test that [it works](https://github.com/kitspace/kitspace-v2/actions/runs/4140118757).
##
Fixes #548

Handle special characters e2e commit info

---

frontend/src/contexts/SearchContext.tsx

Before this commit using the browser history navigation didn't work for
the search. i.e, if you type a `q1` in the search bar, and submit, then type
`q2` and submit, if you go back using the browser button, the page would
still show the results of `q2` instead of `q1`

Fix history navigation for search

---

.github/workflows/docker.yml

The short one seems to be sometimes 8 and sometimes 9 characters depending on what git decides, so we are rebuilding things when we don't need to.

Use full git sha for docker image tags

---

processor/package.json
processor/src/queues.ts
processor/test/integration/projects.test.ts
processor/yarn.lock
scripts/importBoardsTxt.ts

I tried three approaches to handle the registry boards:
1. clone the repo, checkout the hash, create an empty gitea repo, and push to gitea (the most complicated)
2. migrate the repo, clone it, and change the default branch, and push
3. checkout the hash in the processor (the cleanest)
I settled for making the processor handle the registry boards.

Handle registry boards in processor

---

frontend/src/components/Page/index.module.scss

|before|after|
|---|---|
|![image](https://github.com/kitspace/kitspace-v2/assets/37152329/dea34839-f672-4368-90c0-dfde9934602a)|![image](https://github.com/kitspace/kitspace-v2/assets/37152329/07fc9b99-211f-4912-a0bb-21b0318f4b22)|
##
Fixes #581

Fix small screen padding

---

processor/src/queues.ts

Running `importBoartsTxt` on a fresh server (but all repos are already processed)
```
VOLUME NAME                                                        LINKS     SIZE
kitspace-abdo-dev_processor-data                                   1         12.63GB
```
```
VOLUME NAME                                                        LINKS     SIZE
kitspace-abdo-dev_processor-data                                   1         0B
```
##
Fixes #598

Delete the repo if it's already processed

---

frontend/package.json
frontend/yarn.lock

It's no longer used, and dependapot is complaining about `loader-utils`
in several alerts:
1. https://github.com/kitspace/kitspace-v2/security/dependabot/45
2. https://github.com/kitspace/kitspace-v2/security/dependabot/46
3. https://github.com/kitspace/kitspace-v2/security/dependabot/47

Deps: remove `raw-loader`, upgrade `loader-utils`

---

scripts/importBoardsTxt.ts

The flag was only working with `--suffle true`

Fix `numberOfRepos` flag in `scripts/importBoardsTxt.ts`

---

e2e/cypress/support/commands.js
nginx/kitspace.template
nginx/reachability_healthcheck

Proxy api, and raw content requests to gitea, otherwise return 404.
The raw content is for readme images.
Closes #474.

Hide gitea

---

processor/src/tasks/processBOM/get_partinfo.ts
processor/src/tasks/processBOM/index.ts
processor/test/integration/projects.test.ts

Partinfo is still cached parts only, seems it can timeout on new parts right now. All needs to be fixed updated properly eventually of course.

Work around partinfo API timing out

---

docker-compose.yml
processor/src/log.ts
scripts/importBoardsTxt.ts

A sample of the processor logs
```log
[2024-01-19T18:22:54Z]  🚀 Kitspace processor service is running.
[2024-01-19T18:22:54Z]  https://partinfo.kitspace.org/graphql health check passed
[2024-01-19T18:22:54Z]  Acquired sync lock for  /gitea-data/git/repositories/kimitobo/neocococat.git
[2024-01-19T18:22:54Z]  Cloning  /gitea-data/git/repositories/kimitobo/neocococat.git
[2024-01-19T18:22:54Z]  Cloned into /data/checkout/kimitobo/Neocococat
[2024-01-19T18:22:54Z]  Released sync lock for  /gitea-data/git/repositories/kimitobo/neocococat.git
[2024-01-19T18:31:17Z]  Acquired sync lock for  /gitea-data/git/repositories/kimitobo/neocococat.git
[2024-01-19T18:31:17Z]  Cloning  /gitea-data/git/repositories/kimitobo/neocococat.git
[2024-01-19T18:31:17Z]  Cloned into …
```

Set mirror interval to 10 minutes
